# Generated by Django 5.2.7 on 2025-12-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_usuario_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_criacao',
        ),
    ]
