# Generated by Django 5.2.6 on 2025-12-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendencia', models.CharField(max_length=50)),
            ],
        ),
    ]
