# Generated by Django 5.2.7 on 2025-12-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0002_pendencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pendencia',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
